feat(bundler-cli,bundler-core): improved cli input, output and verification
MapColonies/bundler pull request #3
Opened 2023-06-19 15:47 UTC by melancholiai

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✖                                                                       |

2023-06-28 07:51 UTC, syncush requested changes

2023-06-28 07:51 UTC, syncush commented on packages/cli/src/commands/verify/util.ts
> +const MILLISECONDS_IN_SECOND = 1000;
Shouldn't it be nested under common/constants?

2023-06-28 07:51 UTC, syncush commented on packages/core/package.json
> +    "@map-colonies/bundler-common": "*",
once we publish we will set the correct ver, right?

2023-06-28 07:51 UTC, syncush commented on packages/github/src/client/interfaces.ts
> +import { RepositoryId } from '@map-colonies/bundler-common/src';
why are we specifying /src?

2023-07-03 13:51 UTC, melancholiai commented on packages/cli/src/commands/verify/util.ts
> +const MILLISECONDS_IN_SECOND = 1000;
this variable is being used here and here only

2023-07-03 13:51 UTC, melancholiai commented on packages/core/package.json
> +    "@map-colonies/bundler-common": "*",
true

2023-07-03 13:52 UTC, melancholiai commented on packages/github/src/client/interfaces.ts
> +import { RepositoryId } from '@map-colonies/bundler-common/src';
fixed.

2023-07-03 13:52 UTC, syncush approved these changes

2023-07-03 13:53 UTC, merged